# Generated by Django 5.1.2 on 2024-12-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.CharField(error_messages={'unique': '该工号已存在'}, help_text='工号', max_length=300, unique=True, verbose_name='工号'),
        ),
    ]
