# Generated by Django 5.1.2 on 2024-12-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0002_alter_user_employee_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='owner',
            new_name='community',
        ),
    ]
