# Generated by Django 5.1.2 on 2024-12-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0005_alter_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='filename',
            field=models.CharField(default='', max_length=200, verbose_name='文件名'),
            preserve_default=False,
        ),
    ]
