# Generated by Django 5.1.2 on 2024-12-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0006_banner_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='status',
            field=models.IntegerField(default=0, verbose_name='设备状态'),
        ),
    ]
