# Generated by Django 5.1.2 on 2024-12-18 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0007_devices_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecord',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
