# Generated by Django 5.1.2 on 2024-12-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0008_messagerecord_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecord',
            name='execute_person',
            field=models.IntegerField(db_index=True, default=0, verbose_name='当日不文明行为'),
        ),
    ]
