# Generated by Django 5.1.2 on 2024-12-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0009_messagerecord_execute_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', error_messages={'unique': '该地址格式不正确'}, help_text='地址', max_length=200, verbose_name='地址'),
        ),
    ]
