# Generated by Django 5.1.2 on 2024-12-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0010_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pic_url',
            field=models.CharField(default='', max_length=200, verbose_name='图片路径'),
            preserve_default=False,
        ),
    ]
