# Generated by Django 5.1.2 on 2024-12-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0012_task_deal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deal_status',
        ),
    ]
